language: java
jdk:
 - oraclejdk8
 
before_script:
- cd AddressBook2
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

sript: mvm test -B

deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: application
 
