mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
language: java
jdk:
 - oraclejdk8
 
before_script:
- cd AddressBook2
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

sript: mvm test -B
 
